server:
  port: ${SERVER_PORT:18081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://10.10.177.151:3309/data_element_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:iwhale@123}
    hikari:
      pool-name: ${SPRING_DATASOURCE_HIKARI_POOL_NAME:platform-mysql}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:64}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:10}
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  level:
    com.dep: warn
